language: go
go:
  - '1.12'

env:
  - GO111MODULE=on

services:
  - docker

before_install:
  - go install github.com/mattn/goveralls

install:
  - go get

script:
  - go vet
  - gofmt -e -d *.go
  - go build
  - goveralls -race -service=travis-ci
after_success:
  - git status
  - test -n "$TRAVIS_TAG" && docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"

deploy:
- provider: script
  skip_cleanup: true
  script: curl -sL https://git.io/goreleaser | bash
  on:
    tags: true
    condition: $TRAVIS_OS_NAME = linux
